[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.1.0
    kitesurfer1404/WS2812FX @ ^1.4.2

; -------------------------------------------------------------
; OVER-THE-AIR (OTA) UPDATES
; To flash updates wirelessly, uncomment the two lines below 
; and replace the IP with your ESP32's current IP address.
; -------------------------------------------------------------
upload_protocol = espota
upload_port = 192.168.1.190
