[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.1.0
    kitesurfer1404/WS2812FX @ ^1.4.2
